In [4]:
import pandas
import numpy as np
from sklearn.neighbors.classification import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import scale

In [5]:
data = np.genfromtxt('C:\\Users\\User\\Documents\\AI\\ML course\\wine.data', delimiter=',')
y = data[:,0]
x = data[:,1:]

[[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [6]:
kf = KFold(n_splits = 5, shuffle = True, random_state = 42)

for train_index, test_index in kf.split(x):
    print('TRAIN:', train_index, 'TEST:', test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [  0   1   2   3   4   5   6   7   8  10  11  13  14  17  20  21  22  23
  25  26  27  28  32  33  34  35  36  37  38  39  40  43  44  46  47  48
  49  50  51  52  53  54  56  57  58  59  61  62  63  64  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  83  84  85  86  87  88  89  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 110
 112 115 116 120 121 122 123 124 125 126 127 129 130 131 132 133 134 135
 136 137 138 139 142 143 144 146 147 148 149 151 152 153 154 155 156 157
 158 159 160 161 162 163 165 166 167 168 170 172 173 175 176 177] TEST: [  9  12  15  16  18  19  24  29  30  31  41  42  45  55  60  65  66  67
  82  90 109 111 113 114 117 118 119 128 140 141 145 150 164 169 171 174]
TRAIN: [  0   1   3   5   7   8   9  10  12  13  14  15  16  17  18  19  20  21
  23  24  25  28  29  30  31  33  34  35  37  39  40  41  42  43  44  45
  46  47  48  49  50  52  53  54  55  57  58  59  60  61  62  63  64  65
  66  67  70  71  72  73  74  75  77 

In [37]:
from sklearn.preprocessing import normalize

In [43]:
num = 0 
max_cvs = 0

for k in range(1,51): 
    neigh = KNeighborsClassifier(n_neighbors=k) 
    cvs = cross_val_score(neigh, x, y, cv=kf, scoring='accuracy') 
    if np.mean(cvs) > max_cvs: 
        max_cvs = np.mean(cvs) 
        num = k

print (num, max_cvs)

1 0.7304761904761905


In [47]:


x2 = scale(x, axis = 0, with_mean=True, with_std=True, copy=True)

In [48]:
for k in range(1,51): 
    neigh = KNeighborsClassifier(n_neighbors=k) 
    cvs = cross_val_score(neigh, x2, y, cv=kf, scoring='accuracy') 
    if np.mean(cvs) > max_cvs: 
        max_cvs = np.mean(cvs) 
        num = k

print (num, max_cvs)

29 0.9776190476190475
